import type {
  AreaId,
  Customer,
  CustomerType,
  Fulfillment,
  LeadSource,
  PaymentBehavior,
  PaymentTerms,
  StandingOrder,
} from '../domain/types';
import { areaById } from '../domain/data/areas';

interface Row {
  id: string;
  name: string;
  type: CustomerType;
  area: AreaId;
  line1: string;
  brgy: string;
  contact: [name: string, position: string, phone: string];
  alt?: [name: string, position: string, phone: string];
  terms: PaymentTerms;
  limit: number;
  sp: string;
  src: LeadSource;
  since: string;
  prefs: string[];
  ful?: Fulfillment;
  behavior?: PaymentBehavior;
  freq?: number;
  fee?: number;
  hours?: string;
  status?: Customer['status'];
  notes: string;
  landmark?: string;
  extraAddress?: { label: string; line1: string; brgy: string; hours: string };
}

const ROWS: Row[] = [
  // ── Navotas ──────────────────────────────────────────────────────────────
  {
    id: 'CUS-001',
    name: 'Navotas Prime Seafood Supply',
    type: 'Seafood Dealer',
    area: 'navotas',
    line1: 'Stall 14–16, Navotas Fish Port Complex, North Bay Blvd.',
    brgy: 'Brgy. North Bay Boulevard South',
    contact: ['Ernesto Tan', 'Owner', '0917 623 4410'],
    alt: ['Lani Tan', 'Purchasing', '0918 552 0917'],
    terms: 'Credit 7 Days',
    limit: 600000,
    sp: 'ST-02',
    src: 'Referral',
    since: '2023-03-14',
    prefs: ['P-SUG-L', 'P-SUG-J', 'P-TAH', 'P-TAL'],
    behavior: 'prompt',
    freq: 10,
    hours: '5:00 AM – 9:00 AM',
    notes:
      'Largest sugpo buyer. Prefers delivery before 8:00 AM when port buyers arrive. Pays by bank transfer every Friday.',
    landmark: 'Beside the Bagsakan ng Hipon',
  },
  {
    id: 'CUS-002',
    name: 'RJM Seafood Trading',
    type: 'Seafood Dealer',
    area: 'navotas',
    line1: '88 M. Naval St.',
    brgy: 'Brgy. Tangos North',
    contact: ['Rodrigo J. Manalastas', 'Owner', '0927 118 6603'],
    alt: ['Jessa Manalastas', 'Cashier', '0947 220 1185'],
    terms: 'Credit 15 Days',
    limit: 350000,
    sp: 'ST-02',
    src: 'Facebook Group',
    since: '2024-01-09',
    prefs: ['P-SUG-L', 'P-SUG-M', 'P-HIP-W'],
    behavior: 'delinquent',
    freq: 4,
    hours: '6:00 AM – 10:00 AM',
    notes:
      'Good volume but slow to pay. Accounting asked to hold new credit orders once overdue exceeds ₱100,000.',
  },
  {
    id: 'CUS-003',
    name: 'Tangos Bayside Fish Dealer',
    type: 'Seafood Dealer',
    area: 'navotas',
    line1: '221 Estrella St.',
    brgy: 'Brgy. Tangos South',
    contact: ['Lorna Pascual', 'Owner', '0919 774 2036'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-03',
    src: 'Facebook Marketplace',
    since: '2024-06-21',
    prefs: ['P-TAH', 'P-TAL', 'P-TIL'],
    behavior: 'prompt',
    freq: 7,
    hours: '6:00 AM – 11:00 AM',
    notes: 'Cash on delivery only. Supplies tahong and talaba to several Malabon carinderias.',
  },
  {
    id: 'CUS-004',
    name: 'North Bay Seafood Consolidators',
    type: 'Distributor',
    area: 'navotas',
    line1: 'Warehouse 3, C-4 Road',
    brgy: 'Brgy. North Bay Boulevard North',
    contact: ['Vicente Lim', 'General Manager', '0917 405 8821'],
    alt: ['Arnel Santos', 'Receiving Supervisor', '0998 612 4470'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-02',
    src: 'Existing Customer Referral',
    since: '2023-08-02',
    prefs: ['P-TAH', 'P-TAL', 'P-BAN', 'P-SUG-M'],
    behavior: 'average',
    freq: 8,
    hours: '6:00 AM – 2:00 PM',
    notes:
      'Consolidates for Bulacan and Pampanga markets. Pays COD by bank transfer while the truck unloads. Needs DR and invoice copy.',
  },
  {
    id: 'CUS-005',
    name: 'San Roque Fresh Catch',
    type: 'Palengke Vendor',
    area: 'navotas',
    line1: 'Stall B-7, San Roque Public Market',
    brgy: 'Brgy. San Roque',
    contact: ['Myrna dela Cruz', 'Owner', '0936 812 0054'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-03',
    src: 'Facebook Group',
    since: '2025-02-11',
    prefs: ['P-TAH', 'P-HIP-S', 'P-TIL'],
    behavior: 'prompt',
    freq: 5,
    hours: '5:00 AM – 8:00 AM',
    notes: 'Pays via GCash upon delivery.',
  },
  {
    id: 'CUS-046',
    name: 'Bangkulasi Seafood Trading',
    type: 'Seafood Dealer',
    area: 'navotas',
    line1: '45 C-4 Road',
    brgy: 'Brgy. Bangkulasi',
    contact: ['Efren Galang', 'Owner', '0919 802 4415'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-03',
    src: 'Existing Customer Referral',
    since: '2025-10-13',
    prefs: ['P-TAH', 'P-HIP-S', 'P-BAN'],
    behavior: 'prompt',
    freq: 5,
    hours: '6:00 AM – 10:00 AM',
    notes: 'Referred by Lorna of Tangos Bayside.',
  },
  // ── Valenzuela ───────────────────────────────────────────────────────────
  {
    id: 'CUS-006',
    name: 'Maribel Wet Market Trading',
    type: 'Palengke Vendor',
    area: 'valenzuela',
    line1: 'Stalls 32–34, Marulas Public Market, MacArthur Hwy.',
    brgy: 'Brgy. Marulas',
    contact: ['Maribel Santiago', 'Owner', '0917 330 1942'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-03',
    src: 'Messenger',
    since: '2024-04-18',
    prefs: ['P-TAH', 'P-TAL', 'P-HIP-S'],
    behavior: 'prompt',
    freq: 8,
    hours: '6:00 AM – 10:00 AM',
    notes: 'Orders via Messenger the night before. Always COD, cash.',
  },
  {
    id: 'CUS-007',
    name: 'Aling Nena Seafood Stall',
    type: 'Palengke Vendor',
    area: 'valenzuela',
    line1: 'Stall 18, Karuhatan Public Market',
    brgy: 'Brgy. Karuhatan',
    contact: ['Nenita Robles', 'Owner', '0928 470 6618'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-03',
    src: 'Facebook Group',
    since: '2024-09-02',
    prefs: ['P-TAH', 'P-BAN', 'P-TIL'],
    behavior: 'prompt',
    freq: 7,
    hours: '6:00 AM – 10:00 AM',
    notes: 'Loyal suki. Asks for tahong with bigger shells.',
  },
  {
    id: 'CUS-008',
    name: 'Karuhatan Seafood Trading',
    type: 'Seafood Dealer',
    area: 'valenzuela',
    line1: '142 G. Lazaro St.',
    brgy: 'Brgy. Karuhatan',
    contact: ['Ferdinand Ocampo', 'Owner', '0917 881 5530'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-02',
    src: 'Referral',
    since: '2023-11-20',
    prefs: ['P-SUG-L', 'P-SUG-M', 'P-HIP-S', 'P-BAN'],
    behavior: 'average',
    freq: 8,
    hours: '7:00 AM – 12:00 NN',
    notes: 'Pays cash or GCash on delivery; weekly volume discount negotiated.',
  },
  {
    id: 'CUS-009',
    name: 'Malinta Niyog & Gulay Trading',
    type: 'Distributor',
    area: 'valenzuela',
    line1: '56 McArthur Hwy.',
    brgy: 'Brgy. Malinta',
    contact: ['Rogelio Bautista', 'Owner', '0919 206 4417'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-02',
    src: 'Walk-in',
    since: '2024-02-27',
    prefs: ['P-NIY', 'P-SAB', 'P-KAM'],
    behavior: 'prompt',
    freq: 8,
    hours: '8:00 AM – 3:00 PM',
    notes:
      'Bulk buyer of Quezon niyog and saba. Distributes to Bulacan gata vendors. Fills the truck well.',
  },
  {
    id: 'CUS-010',
    name: "Kuya Boyet's Fish Stall",
    type: 'Palengke Vendor',
    area: 'valenzuela',
    line1: 'Stall 5, Marulas Public Market',
    brgy: 'Brgy. Marulas',
    contact: ['Alberto "Boyet" Soriano', 'Owner', '0945 318 7702'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-03',
    src: 'Facebook Marketplace',
    since: '2025-01-15',
    prefs: ['P-HIP-S', 'P-BAN', 'P-TIL'],
    behavior: 'average',
    freq: 6,
    hours: '5:30 AM – 9:00 AM',
    notes: 'Sometimes pays partial, balance on next delivery.',
  },
  {
    id: 'CUS-011',
    name: 'Dalandanan Fresh Seafood',
    type: 'Palengke Vendor',
    area: 'valenzuela',
    line1: 'Stall 22, Dalandanan Market',
    brgy: 'Brgy. Dalandanan',
    contact: ['Cecilia Mariano', 'Owner', '0966 540 2291'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-03',
    src: 'Facebook Page',
    since: '2026-08-10',
    prefs: ['P-TAH', 'P-TIL'],
    behavior: 'prompt',
    freq: 3,
    status: 'new',
    hours: '6:00 AM – 9:00 AM',
    notes: 'New account, first orders placed through the customer portal.',
  },
  // ── Caloocan / QC / Manila ───────────────────────────────────────────────
  {
    id: 'CUS-012',
    name: 'Sangandaan Seafood Supply',
    type: 'Seafood Dealer',
    area: 'caloocan',
    line1: '310 A. Mabini St.',
    brgy: 'Brgy. 8 (Sangandaan)',
    contact: ['Antonio Dizon', 'Owner', '0917 512 9038'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-03',
    src: 'Facebook Group',
    since: '2024-05-06',
    prefs: ['P-HIP-S', 'P-TUL', 'P-PUS', 'P-BAN'],
    behavior: 'average',
    freq: 6,
    hours: '6:00 AM – 11:00 AM',
    notes: 'Also buys tulingan and pusit from Dalahican.',
  },
  {
    id: 'CUS-013',
    name: 'Kamuning Seafood Grill',
    type: 'Restaurant',
    area: 'quezon-city',
    line1: '47 Kamuning Rd.',
    brgy: 'Brgy. Kamuning',
    contact: ['Paolo Guevarra', 'Head Chef', '0918 903 2275'],
    alt: ['Rhea Castillo', 'Purchasing', '0917 144 6630'],
    terms: 'Credit 15 Days',
    limit: 180000,
    sp: 'ST-03',
    src: 'Facebook Page',
    since: '2024-07-30',
    prefs: ['P-SUG-J', 'P-TAH-C', 'P-TAL', 'P-ALI-F'],
    behavior: 'prompt',
    freq: 5,
    fee: 1500,
    hours: '9:00 AM – 11:00 AM',
    notes: 'Standing orders every Mon/Wed/Fri. Receiving at the back entrance on Scout Tuason.',
  },
  {
    id: 'CUS-014',
    name: 'Commonwealth Market — Aling Tess',
    type: 'Palengke Vendor',
    area: 'quezon-city',
    line1: 'Fish Section Stall 41, Commonwealth Market',
    brgy: 'Brgy. Commonwealth',
    contact: ['Teresita Lagman', 'Owner', '0939 610 5874'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-03',
    src: 'Messenger',
    since: '2025-03-19',
    prefs: ['P-TAH', 'P-TIL', 'P-HIP-S'],
    behavior: 'prompt',
    freq: 4,
    hours: '5:00 AM – 8:00 AM',
    notes: '',
  },
  {
    id: 'CUS-015',
    name: 'Muñoz Market Seafood Dealer',
    type: 'Seafood Dealer',
    area: 'quezon-city',
    line1: 'Muñoz Market, Roosevelt Ave.',
    brgy: 'Brgy. Bago Bantay',
    contact: ['Reynaldo Ferrer', 'Owner', '0917 336 8820'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-03',
    src: 'Referral',
    since: '2024-10-11',
    prefs: ['P-SUG-M', 'P-BAN', 'P-TIL', 'P-TAH'],
    behavior: 'average',
    freq: 5,
    hours: '6:00 AM – 10:00 AM',
    notes: '',
  },
  {
    id: 'CUS-016',
    name: 'Hotel Luntian Quezon City',
    type: 'Hotel',
    area: 'quezon-city',
    line1: '12 Timog Ave. cor. Sgt. Esguerra',
    brgy: 'Brgy. South Triangle',
    contact: ['Cheryl Abad', 'Purchasing Officer', '0917 802 3316'],
    alt: ['Chef Martin Uy', 'Executive Chef', '0918 245 7719'],
    terms: 'Credit 30 Days',
    limit: 400000,
    sp: 'ST-02',
    src: 'Referral',
    since: '2024-03-01',
    prefs: ['P-SUG-J', 'P-ALI-F', 'P-TAH-C', 'P-TAL-S', 'P-PUS'],
    behavior: 'average',
    freq: 4,
    fee: 1500,
    hours: '8:00 AM – 11:00 AM (loading bay)',
    notes:
      'Requires vacuum-packed sugpo and accredited supplier documents (BIR 2303, business permit).',
  },
  {
    id: 'CUS-017',
    name: 'Binondo Seafood House',
    type: 'Restaurant',
    area: 'manila',
    line1: '731 Ongpin St.',
    brgy: 'Brgy. 293, Binondo',
    contact: ['Henry Go', 'Owner', '0917 850 1162'],
    terms: 'Credit 15 Days',
    limit: 200000,
    sp: 'ST-03',
    src: 'Existing Customer Referral',
    since: '2024-08-22',
    prefs: ['P-SUG-J', 'P-ALI-F', 'P-ALI-M', 'P-PUS'],
    behavior: 'prompt',
    freq: 5,
    fee: 1500,
    hours: '7:00 AM – 10:00 AM',
    notes: 'Needs live alimango — check crate ventilation.',
  },
  {
    id: 'CUS-018',
    name: 'Paco Market Seafood Trading',
    type: 'Seafood Dealer',
    area: 'manila',
    line1: 'Paco Public Market, Pedro Gil St.',
    brgy: 'Brgy. 670, Paco',
    contact: ['Gilbert Ramos', 'Owner', '0928 117 4453'],
    terms: 'Credit 7 Days',
    limit: 200000,
    sp: 'ST-03',
    src: 'Facebook Group',
    since: '2025-01-06',
    prefs: ['P-SUG-M', 'P-HIP-S', 'P-TAH', 'P-BAN'],
    behavior: 'slow',
    freq: 5,
    hours: '5:00 AM – 9:00 AM',
    notes: '',
  },
  // ── South Metro ──────────────────────────────────────────────────────────
  {
    id: 'CUS-019',
    name: 'Macapagal Seaside Dampa Traders',
    type: 'Seafood Dealer',
    area: 'pasay',
    line1: 'Seaside Dampa, Diosdado Macapagal Blvd.',
    brgy: 'Brgy. 76',
    contact: ['Lucila Samson', 'Owner', '0917 623 0048'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-03',
    src: 'Facebook Page',
    since: '2023-12-12',
    prefs: ['P-SUG-L', 'P-ALI-F', 'P-HIP-W', 'P-PUS'],
    behavior: 'average',
    freq: 6,
    hours: '7:00 AM – 12:00 NN',
    notes: 'Supplies paluto stalls inside the dampa.',
  },
  {
    id: 'CUS-020',
    name: 'Dampa sa Tambo Seafood Paluto',
    type: 'Restaurant',
    area: 'paranaque',
    line1: 'Dampa sa Tambo, Macapagal Ave. Ext.',
    brgy: 'Brgy. Tambo',
    contact: ['Ramil Esguerra', 'Manager', '0998 420 1136'],
    terms: 'Credit 7 Days',
    limit: 150000,
    sp: 'ST-03',
    src: 'Messenger',
    since: '2024-06-04',
    prefs: ['P-SUG-L', 'P-ALI-F', 'P-TAL', 'P-PUS'],
    behavior: 'slow',
    freq: 5,
    fee: 1000,
    hours: '8:00 AM – 12:00 NN',
    notes: 'Often late on payments by 1–2 weeks; follow up via Messenger.',
  },
  {
    id: 'CUS-021',
    name: 'Las Piñas Seafood Distributors',
    type: 'Distributor',
    area: 'las-pinas',
    line1: 'Lot 8, Alabang–Zapote Rd.',
    brgy: 'Brgy. Pamplona Tres',
    contact: ['Cristina Morales', 'Operations Head', '0917 780 6603'],
    alt: ['Jomar Villegas', 'Warehouse', '0927 303 9910'],
    terms: 'Credit 7 Days',
    limit: 500000,
    sp: 'ST-04',
    src: 'Referral',
    since: '2023-09-18',
    prefs: ['P-TAH', 'P-BAN', 'P-TIL', 'P-NIY'],
    behavior: 'average',
    freq: 6,
    hours: '6:00 AM – 3:00 PM',
    notes: 'Distributes to Muntinlupa and Las Piñas palengkes.',
  },
  // ── Cavite ───────────────────────────────────────────────────────────────
  {
    id: 'CUS-022',
    name: 'Seaside Grill Bacoor',
    type: 'Restaurant',
    area: 'bacoor',
    line1: 'Km. 17 Aguinaldo Hwy.',
    brgy: 'Brgy. Niog III',
    contact: ['Marco Villareal', 'Chef-Owner', '0917 921 4406'],
    terms: 'Credit 7 Days',
    limit: 150000,
    sp: 'ST-04',
    src: 'Facebook Page',
    since: '2024-02-05',
    prefs: ['P-SUG-J', 'P-TAH-C', 'P-TAL'],
    behavior: 'prompt',
    freq: 6,
    fee: 2000,
    hours: '10:00 AM – 1:00 PM',
    notes: 'Standing orders Monday and Thursday. Orders through the customer portal.',
  },
  {
    id: 'CUS-023',
    name: 'Cavite Coastal Restaurant',
    type: 'Restaurant',
    area: 'bacoor',
    line1: 'Evangelista St. cor. Molino Blvd.',
    brgy: 'Brgy. Panapaan II',
    contact: ['Ma. Theresa Cabrera', 'Owner', '0918 612 0072'],
    terms: 'Credit 15 Days',
    limit: 200000,
    sp: 'ST-04',
    src: 'Facebook Group',
    since: '2024-05-27',
    prefs: ['P-SUG-L', 'P-TAL', 'P-ALI-F'],
    behavior: 'average',
    freq: 5,
    fee: 1000,
    hours: '10:00 AM – 2:00 PM',
    notes: '',
  },
  {
    id: 'CUS-024',
    name: 'Bacoor Bayside Fish Traders',
    type: 'Seafood Dealer',
    area: 'bacoor',
    line1: '12 Talaba Rd.',
    brgy: 'Brgy. Talaba II',
    contact: ['Danilo Encarnacion', 'Owner', '0919 552 3308'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-04',
    src: 'Walk-in',
    since: '2024-11-04',
    prefs: ['P-TAH', 'P-NIY', 'P-SAB', 'P-BAN'],
    behavior: 'average',
    freq: 6,
    hours: '7:00 AM – 1:00 PM',
    notes: '',
  },
  {
    id: 'CUS-025',
    name: "Nanay Linda's Seafood — Imus Public Market",
    type: 'Palengke Vendor',
    area: 'imus',
    line1: 'Stall 61, Imus Public Market, Nueno Ave.',
    brgy: 'Brgy. Poblacion I-A',
    contact: ['Linda Ancheta', 'Owner', '0935 800 2176'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-04',
    src: 'Facebook Marketplace',
    since: '2024-10-01',
    prefs: ['P-TAH', 'P-BAN', 'P-TIL'],
    behavior: 'prompt',
    freq: 6,
    hours: '10:00 AM – 1:00 PM',
    notes: '',
  },
  {
    id: 'CUS-026',
    name: 'Kusina Caviteño Catering',
    type: 'Catering Company',
    area: 'imus',
    line1: 'Blk 4 Lot 12, Anabu Hills Subd.',
    brgy: 'Brgy. Anabu II-A',
    contact: ['Gerardo Poblete', 'Owner', '0917 250 6649'],
    terms: 'Credit 15 Days',
    limit: 150000,
    sp: 'ST-04',
    src: 'Facebook Page',
    since: '2024-12-09',
    prefs: ['P-SUG-M', 'P-PUS', 'P-BAN-XL', 'P-TAH-C'],
    behavior: 'slow',
    freq: 4,
    fee: 1000,
    hours: '9:00 AM – 3:00 PM',
    notes: 'Volume spikes on weekends (weddings and debuts).',
  },
  {
    id: 'CUS-027',
    name: 'Imus Grand Seafood Trading',
    type: 'Seafood Dealer',
    area: 'imus',
    line1: '88 Gen. Castañeda St.',
    brgy: 'Brgy. Bayan Luma IV',
    contact: ['Wilfredo Saulog', 'Owner', '0918 407 1154'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-04',
    src: 'Referral',
    since: '2024-04-02',
    prefs: ['P-SUG-L', 'P-HIP-S', 'P-BAN'],
    behavior: 'prompt',
    freq: 6,
    hours: '10:00 AM – 2:00 PM',
    notes: '',
  },
  {
    id: 'CUS-028',
    name: 'Dasmariñas Fresh Mart',
    type: 'Grocery',
    area: 'dasmarinas',
    line1: 'Aguinaldo Hwy. cor. Salitran Rd.',
    brgy: 'Brgy. Salitran III',
    contact: ['Joanna Reyes', 'Purchasing', '0917 693 4401'],
    terms: 'Credit 30 Days',
    limit: 300000,
    sp: 'ST-04',
    src: 'Referral',
    since: '2024-06-17',
    prefs: ['P-BAN', 'P-TIL', 'P-TAH-C', 'P-NIY'],
    behavior: 'average',
    freq: 4,
    fee: 1500,
    hours: '7:00 AM – 11:00 AM',
    notes: 'Requires supplier accreditation documents on file.',
  },
  {
    id: 'CUS-029',
    name: 'GenTri Seafood Hub',
    type: 'Seafood Dealer',
    area: 'general-trias',
    line1: 'Arnaldo Hwy., Manggahan Public Market Area',
    brgy: 'Brgy. Manggahan',
    contact: ['Arnold Mercado', 'Owner', '0927 118 4032'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-04',
    src: 'Facebook Group',
    since: '2025-07-14',
    prefs: ['P-TAH', 'P-SUG-M', 'P-BAN'],
    behavior: 'average',
    freq: 4,
    hours: '7:00 AM – 12:00 NN',
    notes: 'Converted from a Facebook Group lead.',
  },
  // ── Laguna / Batangas ────────────────────────────────────────────────────
  {
    id: 'CUS-030',
    name: 'South Luzon Food Distribution',
    type: 'Distributor',
    area: 'calamba',
    line1: 'Warehouse 5, Calamba Premiere Industrial Park',
    brgy: 'Brgy. Batino',
    contact: ['Rafael Umali', 'Purchasing Manager', '0917 408 5520'],
    alt: ['Liza Cortez', 'Accounts Payable', '0918 330 2217'],
    terms: 'Credit 15 Days',
    limit: 900000,
    sp: 'ST-02',
    src: 'Referral',
    since: '2023-06-05',
    prefs: ['P-BAN', 'P-TIL', 'P-TAH', 'P-NIY', 'P-SAB'],
    behavior: 'prompt',
    freq: 5,
    hours: '7:00 AM – 4:00 PM',
    notes: 'Big account. Supplies institutional kitchens across Laguna.',
  },
  {
    id: 'CUS-031',
    name: 'Santa Rosa Grill & Seafood',
    type: 'Restaurant',
    area: 'santa-rosa',
    line1: 'Balibago Complex, Rizal Blvd.',
    brgy: 'Brgy. Balibago',
    contact: ['Cynthia Tolentino', 'Manager', '0998 761 3304'],
    terms: 'Credit 15 Days',
    limit: 150000,
    sp: 'ST-04',
    src: 'Messenger',
    since: '2025-04-08',
    prefs: ['P-SUG-L', 'P-TAL', 'P-PUS'],
    behavior: 'prompt',
    freq: 4,
    fee: 1000,
    hours: '9:00 AM – 12:00 NN',
    notes: '',
  },
  {
    id: 'CUS-032',
    name: 'Pansol Villa Resort & Events',
    type: 'Resort',
    area: 'calamba',
    line1: 'National Hwy.',
    brgy: 'Brgy. Pansol',
    contact: ['Manuel Andal', 'F&B Manager', '0917 330 8819'],
    terms: 'Credit 15 Days',
    limit: 120000,
    sp: 'ST-04',
    src: 'Facebook Page',
    since: '2025-05-20',
    prefs: ['P-SUG-M', 'P-BAN-XL', 'P-TAH-C'],
    behavior: 'average',
    freq: 3,
    fee: 1000,
    hours: '9:00 AM – 2:00 PM',
    notes: 'Weekend event orders.',
  },
  {
    id: 'CUS-033',
    name: 'Batangas Bay Restaurant',
    type: 'Restaurant',
    area: 'batangas-city',
    line1: 'P. Burgos St.',
    brgy: 'Brgy. Pallocan West',
    contact: ['Victor Macalintal', 'Owner', '0917 118 2261'],
    terms: 'Credit 15 Days',
    limit: 150000,
    sp: 'ST-04',
    src: 'Referral',
    since: '2024-08-12',
    prefs: ['P-SUG-J', 'P-TAH-C', 'P-TAL', 'P-ALI-F'],
    behavior: 'prompt',
    freq: 4,
    fee: 1500,
    hours: '8:00 AM – 11:00 AM',
    notes: 'Standing orders on Mon, Wed and Fri. Thursday deliveries via the Batangas run.',
  },
  // ── Lucena & Quezon (bodega pickup) ──────────────────────────────────────
  {
    id: 'CUS-034',
    name: 'Lucena Public Market Trading',
    type: 'Palengke Vendor',
    area: 'lucena',
    line1: 'Stalls 102–105, Lucena City Public Market, Evangelista St.',
    brgy: 'Brgy. 3 (Poblacion)',
    contact: ['Josefina Merle', 'Owner', '0917 603 5528'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-02',
    src: 'Walk-in',
    since: '2023-01-10',
    prefs: ['P-ONR', 'P-ONW', 'P-GAR', 'P-GIN'],
    ful: 'pickup',
    behavior: 'prompt',
    freq: 9,
    hours: 'Pickup 5:00 – 7:00 AM',
    notes: 'Picks up onions and garlic at the bodega daily.',
  },
  {
    id: 'CUS-035',
    name: 'Quezon Harvest Traders',
    type: 'Distributor',
    area: 'sariaya',
    line1: 'Gen. Luna St.',
    brgy: 'Brgy. Poblacion 4',
    contact: ['Alfredo Maaño', 'Owner', '0918 772 1043'],
    terms: 'Credit 7 Days',
    limit: 400000,
    sp: 'ST-02',
    src: 'Referral',
    since: '2023-04-24',
    prefs: ['P-ONR', 'P-ONW', 'P-GAR', 'P-POT', 'P-CAR'],
    ful: 'pickup',
    behavior: 'average',
    freq: 8,
    hours: 'Pickup 8:00 AM – 12:00 NN',
    notes: 'Distributes produce across Sariaya, Candelaria and Tiaong.',
  },
  {
    id: 'CUS-036',
    name: 'Tayabas Gulay Center',
    type: 'Retailer',
    area: 'tayabas',
    line1: 'Tayabas Public Market',
    brgy: 'Brgy. San Diego Zone I',
    contact: ['Consuelo Abrenica', 'Owner', '0935 118 6620'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-02',
    src: 'Walk-in',
    since: '2024-01-22',
    prefs: ['P-ONR', 'P-GAR', 'P-TOM', 'P-POT', 'P-CAB'],
    ful: 'pickup',
    behavior: 'prompt',
    freq: 6,
    hours: 'Pickup 6:00 – 9:00 AM',
    notes: '',
  },
  {
    id: 'CUS-037',
    name: 'Pagbilao Mini-Grocery',
    type: 'Grocery',
    area: 'pagbilao',
    line1: 'Rizal St.',
    brgy: 'Brgy. Poblacion',
    contact: ['Armando Racelis', 'Owner', '0927 551 0829'],
    terms: 'Credit 7 Days',
    limit: 100000,
    sp: 'ST-02',
    src: 'Walk-in',
    since: '2025-06-02',
    prefs: ['P-ONR', 'P-GAR', 'P-POT', 'P-CAR'],
    ful: 'pickup',
    behavior: 'average',
    freq: 4,
    hours: 'Pickup 8:00 AM – 5:00 PM',
    notes: 'Converted from walk-in lead (Gumaca expansion pending).',
  },
  {
    id: 'CUS-038',
    name: "Ate Weng's Gulayan — Candelaria",
    type: 'Palengke Vendor',
    area: 'candelaria',
    line1: 'Candelaria Public Market',
    brgy: 'Brgy. Poblacion',
    contact: ['Wennie Cuevas', 'Owner', '0946 223 7780'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-02',
    src: 'Facebook Marketplace',
    since: '2025-02-17',
    prefs: ['P-ONR', 'P-GAR', 'P-GIN', 'P-TOM'],
    ful: 'pickup',
    behavior: 'prompt',
    freq: 5,
    hours: 'Pickup 6:00 – 9:00 AM',
    notes: '',
  },
  {
    id: 'CUS-039',
    name: 'Hotel Dalahican Bay Lucena',
    type: 'Hotel',
    area: 'lucena',
    line1: 'Dalahican Rd.',
    brgy: 'Brgy. Dalahican',
    contact: ['Jocelyn Villamor', 'Purchasing', '0917 440 3316'],
    terms: 'Credit 30 Days',
    limit: 200000,
    sp: 'ST-02',
    src: 'Referral',
    since: '2024-09-09',
    prefs: ['P-SUG-J', 'P-ALI-F', 'P-TUL', 'P-ONR', 'P-GAR'],
    ful: 'pickup',
    behavior: 'average',
    freq: 4,
    hours: 'Hotel van pickup 7:00 – 9:00 AM',
    notes: 'Sends own van to the bodega.',
  },
  {
    id: 'CUS-040',
    name: 'Pansitan ni Aling Charing',
    type: 'Restaurant',
    area: 'lucena',
    line1: 'Quezon Ave.',
    brgy: 'Brgy. Gulang-Gulang',
    contact: ['Rosario Zaballero', 'Owner', '0928 663 0415'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-02',
    src: 'Walk-in',
    since: '2024-03-11',
    prefs: ['P-ONR', 'P-GAR', 'P-CAR', 'P-CAB'],
    ful: 'pickup',
    behavior: 'prompt',
    freq: 5,
    hours: 'Pickup 7:00 – 10:00 AM',
    notes: 'Pancit Habhab place — buys carrots, cabbage and garlic.',
  },
  // ── Visayas & Mindanao (via sea-freight partner) ─────────────────────────
  {
    id: 'CUS-041',
    name: 'Cebu Seaboard Distributors',
    type: 'Distributor',
    area: 'cebu',
    line1: 'Pier 3 Area, M.J. Cuenco Ave.',
    brgy: 'Brgy. Tinago',
    contact: ['Julius Uy', 'Purchasing Head', '0917 322 8805'],
    terms: '50% Down, Balance on Arrival',
    limit: 600000,
    sp: 'ST-02',
    src: 'Facebook Group',
    since: '2025-01-28',
    prefs: ['P-GIN', 'P-GAR', 'P-SUG-L'],
    ful: 'partner',
    behavior: 'prompt',
    freq: 2,
    hours: 'Consignee warehouse 8:00 AM – 5:00 PM',
    notes: 'Ships via Isla Reefer Cargo through Batangas Port. 50% DP before loading.',
  },
  {
    id: 'CUS-042',
    name: 'Davao Gulf Fresh Trading',
    type: 'Distributor',
    area: 'davao',
    line1: 'R. Castillo St.',
    brgy: 'Brgy. Agdao Proper',
    contact: ['Leonardo Cabahug', 'Owner', '0918 450 9913'],
    terms: '50% Down, Balance on Arrival',
    limit: 500000,
    sp: 'ST-02',
    src: 'Referral',
    since: '2025-04-15',
    prefs: ['P-ONR', 'P-GIN', 'P-NIY'],
    ful: 'partner',
    behavior: 'average',
    freq: 1,
    hours: '8:00 AM – 5:00 PM',
    notes: 'Monthly consolidated shipments.',
  },
  {
    id: 'CUS-043',
    name: 'Iloilo Fresh Consolidators',
    type: 'Distributor',
    area: 'iloilo',
    line1: 'Muelle Loney St.',
    brgy: 'Brgy. Lapuz',
    contact: ['Ma. Cristina Gonzaga', 'Operations', '0917 704 5518'],
    terms: '50% Down, Balance on Arrival',
    limit: 400000,
    sp: 'ST-02',
    src: 'Messenger',
    since: '2025-06-30',
    prefs: ['P-SUG-L', 'P-GIN'],
    ful: 'partner',
    behavior: 'prompt',
    freq: 1,
    hours: '8:00 AM – 5:00 PM',
    notes: 'Frozen-pack sugpo via reefer only.',
  },
  {
    id: 'CUS-044',
    name: 'CDO Northern Mindanao Distributors',
    type: 'Distributor',
    area: 'cagayan-de-oro',
    line1: 'Agora Market Complex',
    brgy: 'Brgy. Lapasan',
    contact: ['Ramon Pacana', 'Owner', '0918 225 6107'],
    terms: '50% Down, Balance on Arrival',
    limit: 400000,
    sp: 'ST-02',
    src: 'Facebook Group',
    since: '2025-08-05',
    prefs: ['P-ONR', 'P-GAR'],
    ful: 'partner',
    behavior: 'average',
    freq: 1,
    hours: '8:00 AM – 5:00 PM',
    notes: '',
  },
  {
    id: 'CUS-045',
    name: 'Bacolod Seafood & Produce Ventures',
    type: 'Distributor',
    area: 'bacolod',
    line1: 'Libertad Public Market Area',
    brgy: 'Brgy. 33',
    contact: ['Anna Marie Lacson', 'Purchasing', '0917 188 4402'],
    terms: '50% Down, Balance on Arrival',
    limit: 300000,
    sp: 'ST-02',
    src: 'Facebook Group',
    since: '2026-07-21',
    prefs: ['P-GIN', 'P-ONR'],
    ful: 'partner',
    behavior: 'prompt',
    freq: 1,
    status: 'new',
    hours: '8:00 AM – 5:00 PM',
    notes: 'Converted from Facebook Group lead in July.',
  },
];

/** Logistics-only accounts: Quezon shippers and backhaul customers who book freight but do not buy product. */
const LOGISTICS_ROWS: Row[] = [
  {
    id: 'CUS-047',
    name: 'Dalahican Seafood Consolidators',
    type: 'Seafood Dealer',
    area: 'lucena',
    line1: 'Bldg. B, Dalahican Fish Port Complex',
    brgy: 'Brgy. Dalahican',
    contact: ['Rolando Abuel', 'Owner', '0917 540 2268'],
    alt: ['Mylene Abuel', 'Dispatch', '0928 116 7045'],
    terms: 'Credit 7 Days',
    limit: 250000,
    sp: 'ST-02',
    src: 'Referral',
    since: '2024-02-12',
    prefs: [],
    behavior: 'prompt',
    freq: 7,
    hours: 'Cargo drop-off 10:00 PM – 2:00 AM',
    notes:
      'Ships sugpo and pusit to Manila buyers 3–4× a week. Books van space the night before via Messenger.',
  },
  {
    id: 'CUS-048',
    name: 'Tayabas Agri Supply',
    type: 'Agri Trader',
    area: 'tayabas',
    line1: 'Quezon Ave. cor. Mabini St.',
    brgy: 'Brgy. San Roque Zone I',
    contact: ['Nestor Villaflor', 'Owner', '0928 604 3317'],
    terms: 'Credit 7 Days',
    limit: 150000,
    sp: 'ST-02',
    src: 'Walk-in',
    since: '2025-03-03',
    prefs: [],
    behavior: 'average',
    freq: 5,
    hours: 'Receiving 6:00 AM – 9:00 PM',
    notes:
      'Buys onions and potatoes in Valenzuela and Balintawak; we haul them home on return legs.',
  },
  {
    id: 'CUS-049',
    name: 'Candelaria Produce Traders',
    type: 'Agri Trader',
    area: 'candelaria',
    line1: 'Rizal Ave.',
    brgy: 'Brgy. Poblacion',
    contact: ['Lucia Barrameda', 'Owner', '0935 772 1049'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-02',
    src: 'Facebook Page',
    since: '2025-11-17',
    prefs: [],
    behavior: 'prompt',
    freq: 4,
    hours: 'Receiving 5:00 PM – 10:00 PM',
    notes: 'Backhaul customer — potatoes, carrots and cabbage from Santa Rosa and Calamba.',
  },
  {
    id: 'CUS-050',
    name: 'Sariaya Feeds & General Merchandise',
    type: 'General Merchandise',
    area: 'sariaya',
    line1: 'Maharlika Hwy.',
    brgy: 'Brgy. Castañas',
    contact: ['Benjie Magpantay', 'Owner', '0919 330 5582'],
    terms: 'Credit 15 Days',
    limit: 200000,
    sp: 'ST-02',
    src: 'Referral',
    since: '2024-10-07',
    prefs: [],
    behavior: 'slow',
    freq: 4,
    hours: 'Receiving 7:00 AM – 9:00 PM',
    notes:
      'Hauls feeds, rice and dry goods from Calamba and Valenzuela warehouses. Pays late — follow up every Friday.',
  },
  {
    id: 'CUS-051',
    name: 'Pagbilao Aqua Farmers Cooperative',
    type: 'Cooperative',
    area: 'pagbilao',
    line1: 'Binahaan Rd.',
    brgy: 'Brgy. Binahaan',
    contact: ['Edna Salvacion', 'Manager', '0936 118 2204'],
    terms: 'Credit 15 Days',
    limit: 180000,
    sp: 'ST-02',
    src: 'Existing Customer Referral',
    since: '2025-06-09',
    prefs: [],
    behavior: 'average',
    freq: 3,
    hours: 'Receiving 7:00 AM – 8:00 PM',
    notes: 'Buys aquaculture feeds and nets in Calamba for member fishpond operators.',
  },
  {
    id: 'CUS-052',
    name: 'Lucena Frozen Goods Depot',
    type: 'Distributor',
    area: 'lucena',
    line1: 'Diversion Rd.',
    brgy: 'Brgy. Ibabang Dupay',
    contact: ['Gregorio Tan', 'Owner', '0917 205 6681'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-02',
    src: 'Messenger',
    since: '2026-08-18',
    prefs: [],
    behavior: 'prompt',
    freq: 2,
    status: 'new',
    hours: 'Receiving 6:00 AM – 10:00 PM',
    notes: 'Occasional third-party frozen goods from Caloocan cold storage.',
  },
  {
    id: 'CUS-053',
    name: 'Masin Agrivet Supply',
    type: 'Retailer',
    area: 'candelaria',
    line1: 'Maharlika Hwy.',
    brgy: 'Brgy. Masin Norte',
    contact: ['Jessa Umali', 'Owner', '0916 482 3307'],
    terms: 'COD',
    limit: 0,
    sp: 'ST-02',
    src: 'Backhaul Marketplace',
    since: '2026-09-25',
    prefs: [],
    behavior: 'prompt',
    freq: 2,
    status: 'new',
    hours: 'Receiving 7:00 AM – 9:00 PM',
    notes:
      'Found us through the Backhaul Marketplace (BKR-260925-001). Buys feeds at Calamba depots. COD until credit review.',
  },
];

function toCustomer(r: Row): Customer {
  const area = areaById(r.area);
  const contacts = [
    { name: r.contact[0], position: r.contact[1], phone: r.contact[2], primary: true },
    ...(r.alt ? [{ name: r.alt[0], position: r.alt[1], phone: r.alt[2] }] : []),
  ];
  const addresses = [
    {
      id: `${r.id}-A1`,
      label:
        r.ful === 'pickup'
          ? 'Business address (bodega pickup)'
          : r.prefs.length === 0
            ? 'Main address'
            : 'Main receiving',
      line1: r.line1,
      barangay: r.brgy,
      city: area.name,
      province: area.province,
      areaId: r.area,
      landmark: r.landmark,
      receivingHours: r.hours ?? '6:00 AM – 12:00 NN',
      default: true,
    },
    ...(r.extraAddress
      ? [
          {
            id: `${r.id}-A2`,
            label: r.extraAddress.label,
            line1: r.extraAddress.line1,
            barangay: r.extraAddress.brgy,
            city: area.name,
            province: area.province,
            areaId: r.area,
            receivingHours: r.extraAddress.hours,
          },
        ]
      : []),
  ];
  const customer: Customer = {
    id: r.id,
    name: r.name,
    type: r.type,
    areaId: r.area,
    contacts,
    addresses,
    paymentTerms: r.terms,
    creditLimit: r.limit,
    salespersonId: r.sp,
    leadSource: r.src,
    customerSince: r.since,
    preferredProductIds: r.prefs,
    fulfillment: r.ful ?? 'truck',
    status: r.status ?? 'active',
    notes: r.notes,
    deliveryFee: r.fee ?? 0,
    paymentBehavior: r.behavior ?? 'average',
    frequency: r.freq ?? 5,
  };
  return customer;
}

/** Accounts used by the trading (product sales) generator. */
export const TRADING_CUSTOMERS: Customer[] = ROWS.map(toCustomer);
export const CUSTOMERS: Customer[] = [...TRADING_CUSTOMERS, ...LOGISTICS_ROWS.map(toCustomer)];

// A few accounts keep a second delivery point.
CUSTOMERS.find((c) => c.id === 'CUS-004')!.addresses.push({
  id: 'CUS-004-A2',
  label: 'Malabon satellite bodega',
  line1: '17 Gov. Pascual Ave.',
  barangay: 'Brgy. Acacia',
  city: 'Malabon City',
  province: 'Metro Manila',
  areaId: 'navotas',
  receivingHours: '7:00 AM – 12:00 NN',
});
CUSTOMERS.find((c) => c.id === 'CUS-016')!.addresses.push({
  id: 'CUS-016-A2',
  label: 'Commissary kitchen',
  line1: '22 Scout Rallos St.',
  barangay: 'Brgy. Laging Handa',
  city: 'Quezon City',
  province: 'Metro Manila',
  areaId: 'quezon-city',
  receivingHours: '8:00 AM – 12:00 NN',
});

const customerMap = new Map(CUSTOMERS.map((c) => [c.id, c]));
export const customerById = (id: string) => customerMap.get(id);

export const STANDING_ORDERS: StandingOrder[] = [
  {
    id: 'SO-001',
    customerId: 'CUS-008',
    day: 'Monday',
    lines: [{ productId: 'P-SUG-L', quantity: 80 }],
    status: 'active',
    startDate: '2025-10-06',
    notes: 'Weekly base order — extras added by phone.',
  },
  {
    id: 'SO-002',
    customerId: 'CUS-008',
    day: 'Wednesday',
    lines: [{ productId: 'P-TAH', quantity: 100 }],
    status: 'active',
    startDate: '2025-10-06',
  },
  {
    id: 'SO-003',
    customerId: 'CUS-008',
    day: 'Friday',
    lines: [
      { productId: 'P-SUG-L', quantity: 100 },
      { productId: 'P-TAL', quantity: 50 },
    ],
    status: 'active',
    startDate: '2025-10-06',
  },
  {
    id: 'SO-004',
    customerId: 'CUS-022',
    day: 'Monday',
    lines: [{ productId: 'P-SUG-J', quantity: 80 }],
    status: 'active',
    startDate: '2026-06-01',
    notes: 'For the Monday seafood boodle special.',
  },
  {
    id: 'SO-005',
    customerId: 'CUS-022',
    day: 'Thursday',
    lines: [
      { productId: 'P-TAH-C', quantity: 120 },
      { productId: 'P-TAL', quantity: 60 },
    ],
    status: 'active',
    startDate: '2026-06-01',
  },
  {
    id: 'SO-006',
    customerId: 'CUS-033',
    day: 'Wednesday',
    lines: [
      { productId: 'P-SUG-J', quantity: 60 },
      { productId: 'P-TAH-C', quantity: 50 },
    ],
    status: 'active',
    startDate: '2026-03-04',
  },
  {
    id: 'SO-007',
    customerId: 'CUS-013',
    day: 'Thursday',
    lines: [
      { productId: 'P-SUG-J', quantity: 60 },
      { productId: 'P-TAH-C', quantity: 40 },
      { productId: 'P-TAL', quantity: 30 },
    ],
    status: 'active',
    startDate: '2025-11-06',
  },
  {
    id: 'SO-008',
    customerId: 'CUS-016',
    day: 'Thursday',
    lines: [
      { productId: 'P-SUG-J', quantity: 40 },
      { productId: 'P-ALI-F', quantity: 15 },
    ],
    status: 'paused',
    startDate: '2025-11-06',
    notes: 'Paused during hotel kitchen renovation until Oct 5.',
  },
  {
    id: 'SO-009',
    customerId: 'CUS-001',
    day: 'Wednesday',
    lines: [{ productId: 'P-SUG-L', quantity: 250 }],
    status: 'active',
    startDate: '2025-01-08',
  },
  {
    id: 'SO-010',
    customerId: 'CUS-034',
    day: 'Monday',
    lines: [
      { productId: 'P-ONR', quantity: 300 },
      { productId: 'P-GAR', quantity: 100 },
    ],
    status: 'active',
    startDate: '2025-05-05',
  },
  {
    id: 'SO-011',
    customerId: 'CUS-030',
    day: 'Tuesday',
    lines: [
      { productId: 'P-BAN', quantity: 400 },
      { productId: 'P-TIL', quantity: 300 },
    ],
    status: 'active',
    startDate: '2025-09-02',
  },
];
