import type { MaintenanceRecord, VehicleDocument } from '../domain/types';

/** Workshop records. Trip-side roadside repairs are logged as trip expenses instead. */
export const MAINTENANCE: MaintenanceRecord[] = [
  // Truck 01 — Isuzu Giga
  {
    id: 'MNT-001',
    truckId: 'TRK-01',
    type: 'Tire Replacement',
    date: '2026-07-02',
    odometerKm: 271420,
    vendor: 'Lucena Tire Supply',
    cost: 76000,
    notes: 'Replaced 4 rear drive tires (11R22.5).',
    nextServiceKm: 331420,
    status: 'Completed',
    downtimeHours: 4,
  },
  {
    id: 'MNT-002',
    truckId: 'TRK-01',
    type: 'Preventive Maintenance',
    date: '2026-09-01',
    odometerKm: 279960,
    vendor: 'Isuzu Service Center, Lucena',
    cost: 24650,
    notes: 'PMS — engine oil, fuel & air filters, greasing. Interval 10,000 km.',
    nextServiceDate: '2026-10-30',
    nextServiceKm: 290000,
    status: 'Completed',
    downtimeHours: 8,
  },
  {
    id: 'MNT-003',
    truckId: 'TRK-01',
    type: 'Brake Service',
    date: '2026-09-14',
    odometerKm: 282130,
    vendor: 'Quezon Heavy Truck Services, Lucena',
    cost: 38400,
    notes:
      'Rear brake chamber and brake lining replacement (axle 2). Truck off the road for the day.',
    status: 'Completed',
    downtimeHours: 22,
  },
  {
    id: 'MNT-004',
    truckId: 'TRK-01',
    type: 'Other',
    date: '2026-09-21',
    odometerKm: 284000,
    vendor: 'Lucena Tire Supply',
    cost: 2800,
    notes: 'Tire rotation and alignment check — deferred twice because of Navotas bookings.',
    status: 'Scheduled',
  },
  {
    id: 'MNT-005',
    truckId: 'TRK-01',
    type: 'Aircon',
    date: '2026-10-03',
    odometerKm: 285900,
    vendor: 'Coolmaster Auto Aircon, Lucena',
    cost: 6500,
    notes: 'Cab aircon cleaning and freon top-up (drivers reported weak cooling).',
    status: 'Scheduled',
  },
  {
    id: 'MNT-006',
    truckId: 'TRK-01',
    type: 'Body Repair',
    date: '2026-05-18',
    odometerKm: 262300,
    vendor: 'Batangas Van Body Works',
    cost: 18900,
    notes: 'Insulation panel repair and rear door seal replacement.',
    status: 'Completed',
    downtimeHours: 30,
  },
  // Truck 02 — Hino 500
  {
    id: 'MNT-007',
    truckId: 'TRK-02',
    type: 'Electrical',
    date: '2026-06-22',
    odometerKm: 180950,
    vendor: 'Lucena Auto Electrical',
    cost: 14200,
    notes: 'Alternator rebuild and battery replacement.',
    status: 'Completed',
    downtimeHours: 12,
  },
  {
    id: 'MNT-008',
    truckId: 'TRK-02',
    type: 'Oil Change',
    date: '2026-08-03',
    odometerKm: 188420,
    vendor: 'Hino Service Center, Calamba',
    cost: 9800,
    notes:
      'Engine oil and oil filter change; brake and suspension inspection after a Pasay pothole impact.',
    status: 'Completed',
    downtimeHours: 3,
  },
  {
    id: 'MNT-009',
    truckId: 'TRK-02',
    type: 'Preventive Maintenance',
    date: '2026-09-08',
    odometerKm: 194880,
    vendor: 'Hino Service Center, Calamba',
    cost: 22300,
    notes:
      'PMS — oil change, filters, clutch adjustment. Interval 5,000 km (heavy stop-and-go use).',
    nextServiceDate: '2026-10-20',
    nextServiceKm: 200000,
    status: 'Completed',
    downtimeHours: 10,
  },
  {
    id: 'MNT-010',
    truckId: 'TRK-02',
    type: 'Brake Service',
    date: '2026-09-28',
    odometerKm: 199600,
    vendor: 'Quezon Heavy Truck Services, Lucena',
    cost: 18500,
    notes: 'Front brake pads and drum resurfacing. Truck unavailable Monday.',
    status: 'Scheduled',
  },
  {
    id: 'MNT-011',
    truckId: 'TRK-02',
    type: 'Engine Repair',
    date: '2026-04-14',
    odometerKm: 169300,
    vendor: 'Hino Service Center, Calamba',
    cost: 41500,
    notes: 'Injector cleaning and turbo hose replacement.',
    status: 'Completed',
    downtimeHours: 26,
  },
];

export const VEHICLE_DOCUMENTS: VehicleDocument[] = [
  {
    id: 'DOC-001',
    type: 'OR/CR',
    truckId: 'TRK-01',
    reference: 'CR No. ••••-4471',
    issuer: 'LTO Lucena District Office',
    issueDate: '2026-03-28',
    expiryDate: '2027-03-31',
    attachment: 'TRK01-ORCR-2026.pdf',
  },
  {
    id: 'DOC-002',
    type: 'Comprehensive Insurance',
    truckId: 'TRK-01',
    reference: 'Policy CV-••••-8812',
    issuer: 'Southern Tagalog Mutual Insurance (demo)',
    issueDate: '2026-02-14',
    expiryDate: '2027-02-14',
    attachment: 'TRK01-insurance.pdf',
  },
  {
    id: 'DOC-003',
    type: 'CTPL Insurance',
    truckId: 'TRK-01',
    reference: 'COC ••••5520',
    issuer: 'Southern Tagalog Mutual Insurance (demo)',
    issueDate: '2026-03-20',
    expiryDate: '2027-03-20',
  },
  {
    id: 'DOC-004',
    type: 'Emission Test',
    truckId: 'TRK-01',
    reference: 'PETC ••••-0931',
    issuer: 'Lucena Emission Testing Center',
    issueDate: '2026-03-26',
    expiryDate: '2027-03-26',
  },
  {
    id: 'DOC-005',
    type: 'LTFRB Franchise (CPC)',
    truckId: 'TRK-01',
    reference: 'Case No. 2022-••••-TH',
    issuer: 'LTFRB Region IV-A',
    issueDate: '2022-01-17',
    expiryDate: '2027-01-17',
    attachment: 'TRK01-CPC.pdf',
    notes: 'Trucks-for-hire franchise covering Region IV-A to NCR.',
  },
  {
    id: 'DOC-006',
    type: 'Fish Port Gate Pass',
    truckId: 'TRK-01',
    reference: 'NFPC-TP-••••18',
    issuer: 'Navotas Fish Port Complex (demo)',
    issueDate: '2026-07-01',
    expiryDate: '2026-12-31',
  },
  {
    id: 'DOC-007',
    type: 'OR/CR',
    truckId: 'TRK-02',
    reference: 'CR No. ••••-9026',
    issuer: 'LTO Lucena District Office',
    issueDate: '2026-06-26',
    expiryDate: '2027-06-30',
    attachment: 'TRK02-ORCR-2026.pdf',
  },
  {
    id: 'DOC-008',
    type: 'Comprehensive Insurance',
    truckId: 'TRK-02',
    reference: 'Policy CV-••••-3347',
    issuer: 'Southern Tagalog Mutual Insurance (demo)',
    issueDate: '2025-10-12',
    expiryDate: '2026-10-12',
    attachment: 'TRK02-insurance.pdf',
    notes: 'Renewal quote requested from broker.',
  },
  {
    id: 'DOC-009',
    type: 'CTPL Insurance',
    truckId: 'TRK-02',
    reference: 'COC ••••7713',
    issuer: 'Southern Tagalog Mutual Insurance (demo)',
    issueDate: '2026-06-20',
    expiryDate: '2027-06-20',
  },
  {
    id: 'DOC-010',
    type: 'Emission Test',
    truckId: 'TRK-02',
    reference: 'PETC ••••-4418',
    issuer: 'Lucena Emission Testing Center',
    issueDate: '2026-06-24',
    expiryDate: '2027-06-24',
  },
  {
    id: 'DOC-011',
    type: 'LTFRB Franchise (CPC)',
    truckId: 'TRK-02',
    reference: 'Case No. 2021-••••-TH',
    issuer: 'LTFRB Region IV-A',
    issueDate: '2021-11-08',
    expiryDate: '2026-11-08',
    notes: 'Extension application to be filed before Oct 25.',
  },
  {
    id: 'DOC-012',
    type: 'Fish Port Gate Pass',
    truckId: 'TRK-02',
    reference: 'NFPC-TP-••••24',
    issuer: 'Navotas Fish Port Complex (demo)',
    issueDate: '2026-07-01',
    expiryDate: '2026-09-20',
    notes: 'Q3 pass lapsed — Truck 02 cannot enter the port complex until renewed.',
  },
  {
    id: 'DOC-013',
    type: "Driver's License",
    driverId: 'DRV-01',
    reference: 'D07-19-••••12',
    issuer: 'LTO',
    issueDate: '2024-04-17',
    expiryDate: '2029-04-17',
  },
  {
    id: 'DOC-014',
    type: "Driver's License",
    driverId: 'DRV-02',
    reference: 'D07-16-••••73',
    issuer: 'LTO',
    issueDate: '2021-11-02',
    expiryDate: '2026-11-02',
    notes: 'Renewal appointment booked Oct 14.',
  },
  {
    id: 'DOC-015',
    type: "Driver's License",
    driverId: 'DRV-03',
    reference: 'D07-20-••••34',
    issuer: 'LTO',
    issueDate: '2025-01-25',
    expiryDate: '2030-01-25',
  },
  {
    id: 'DOC-016',
    type: "Driver's License",
    driverId: 'DRV-04',
    reference: 'D07-21-••••06',
    issuer: 'LTO',
    issueDate: '2021-07-09',
    expiryDate: '2031-07-09',
  },
  {
    id: 'DOC-017',
    type: 'NBI Clearance',
    driverId: 'DRV-03',
    reference: 'NBI ••••-2291',
    issuer: 'NBI Lucena Satellite Office',
    issueDate: '2025-09-18',
    expiryDate: '2026-09-18',
    notes: 'Expired — required by Hotel Luntian receiving.',
  },
  {
    id: 'DOC-018',
    type: 'Drug Test',
    driverId: 'DRV-04',
    reference: 'DT-••••61',
    issuer: 'DOH-accredited clinic, Lucena',
    issueDate: '2026-04-02',
    expiryDate: '2027-04-02',
  },
  {
    id: 'DOC-019',
    type: 'NBI Clearance',
    driverId: 'DRV-01',
    reference: 'NBI ••••-1175',
    issuer: 'NBI Lucena Satellite Office',
    issueDate: '2026-01-12',
    expiryDate: '2027-01-12',
  },
];
