import type { Lead } from '../domain/types';

/** Freight prospects: shippers and consignees who could book van space on our lanes. */
export const LEADS: Lead[] = [
  {
    id: 'LD-001',
    businessName: 'JM Seafood Dealer',
    contactName: 'Jomar Manalo',
    phone: '0917 440 2281',
    source: 'Facebook Group',
    location: 'Imus, Cavite',
    areaId: 'imus',
    businessType: 'Seafood Dealer',
    cargoInterest: 'Sugpo, iced (styro boxes)',
    lane: 'Lucena → Imus',
    potentialVolume: '≈600 kg × 2 trips/week',
    potentialMonthlyValue: 48000,
    stage: 'Quoted',
    ownerId: 'ST-04',
    createdAt: '2026-09-14',
    lastContactAt: '2026-09-23',
    nextStep: "Follow up on QT-260924-002; offer first run on Monday's Cavite trip",
    activities: [
      {
        at: '2026-09-14T20:12',
        note: "Commented on our post in 'Cavite Seafood Buyers & Sellers' asking who hauls sugpo from Quezon.",
        by: 'Aileen Macaraeg',
      },
      {
        at: '2026-09-16T10:30',
        note: "Called. Currently uses a Bacoor middleman's truck — often late and no POD.",
        by: 'Aileen Macaraeg',
      },
      {
        at: '2026-09-23T15:05',
        note: 'Sent quotation QT-260924-002 via Messenger: ₱6,000 per 600 kg run + re-icing.',
        by: 'Aileen Macaraeg',
      },
    ],
  },
  {
    id: 'LD-002',
    businessName: "Rosa's Ihaw-Ihaw",
    contactName: 'Rosa Villanueva',
    phone: '0928 715 6620',
    source: 'Messenger',
    location: 'Teachers Village, Quezon City',
    areaId: 'quezon-city',
    businessType: 'Restaurant',
    cargoInterest: 'Tahong and talaba from Pagbilao suppliers',
    lane: 'Lucena → Quezon City',
    potentialVolume: '≈180 kg/week',
    potentialMonthlyValue: 8400,
    stage: 'Lost',
    ownerId: 'ST-03',
    createdAt: '2026-09-08',
    lastContactAt: '2026-09-21',
    lostReason: 'Prefers to pick up with a hired L300 van — cheaper for 180 kg.',
    activities: [
      {
        at: '2026-09-08T21:40',
        note: 'Messaged our FB page asking if we can haul shellfish to QC.',
        by: 'Jerome Bautista',
      },
      {
        at: '2026-09-18T09:20',
        note: 'Sent QT-260918-001 (₱2,100 per drop).',
        by: 'Jerome Bautista',
      },
      {
        at: '2026-09-21T13:00',
        note: 'Declined — will hire a small van instead.',
        by: 'Jerome Bautista',
      },
    ],
  },
  {
    id: 'LD-003',
    businessName: 'Kalye Seafood Paluto',
    contactName: 'Edgar Samaniego',
    phone: '0917 330 9914',
    source: 'Facebook Page',
    location: 'Pasay City',
    areaId: 'pasay',
    businessType: 'Restaurant',
    cargoInterest: 'Mixed seafood from Dalahican',
    lane: 'Lucena → Pasay',
    potentialVolume: '≈300 kg × 2 trips/week',
    potentialMonthlyValue: 26000,
    stage: 'Negotiating',
    ownerId: 'ST-03',
    createdAt: '2026-08-27',
    lastContactAt: '2026-09-22',
    nextStep: 'Negotiating Credit 15 days on freight — escalate to Kristine',
    activities: [
      {
        at: '2026-08-27T13:00',
        note: 'Inquiry from FB page ad about scheduled Pasay drops.',
        by: 'Jerome Bautista',
      },
      {
        at: '2026-09-22T16:45',
        note: 'Owner wants Credit 15 days from first booking. Escalated to Kristine.',
        by: 'Jerome Bautista',
      },
    ],
  },
  {
    id: 'LD-004',
    businessName: 'Tagaytay Ridge Bistro',
    contactName: 'Camille Aquino',
    phone: '0918 206 3348',
    source: 'Referral',
    location: 'Tagaytay City, Cavite',
    businessType: 'Restaurant',
    cargoInterest: 'Sugpo and tahong',
    lane: 'Lucena → Tagaytay (via Dasmariñas)',
    potentialVolume: '≈120 kg/week',
    potentialMonthlyValue: 7200,
    stage: 'New',
    ownerId: 'ST-04',
    createdAt: '2026-09-24',
    lastContactAt: '2026-09-24',
    nextStep: 'Call to introduce; check if Tagaytay can join the Dasmariñas stop',
    activities: [
      {
        at: '2026-09-24T17:30',
        note: 'Referred by Chef Marco of Seaside Grill Bacoor.',
        by: 'Aileen Macaraeg',
      },
    ],
  },
  {
    id: 'LD-005',
    businessName: 'San Pablo Palengke Vendors Association',
    contactName: 'Rodel Brion',
    phone: '0936 552 1019',
    source: 'Walk-in',
    location: 'San Pablo City, Laguna',
    businessType: 'Palengke Vendor',
    cargoInterest: 'Tahong and tilapia (group booking)',
    lane: 'Lucena → San Pablo',
    potentialVolume: '≈600 kg/week',
    potentialMonthlyValue: 19200,
    stage: 'Contacted',
    ownerId: 'ST-02',
    createdAt: '2026-09-12',
    lastContactAt: '2026-09-19',
    nextStep: 'Presentation at association meeting, Oct 1 — bring QT-260925-001',
    activities: [
      {
        at: '2026-09-12T10:00',
        note: 'Association president visited the Lucena bodega to see the vans.',
        by: 'Kristine Ramos',
      },
    ],
  },
  {
    id: 'LD-006',
    businessName: 'Sta. Cruz Agri Hub',
    contactName: 'Perla Valdez',
    phone: '0935 330 2208',
    source: 'Facebook Page',
    location: 'Santa Cruz, Laguna',
    businessType: 'Agri Trader',
    cargoInterest: 'Onions and garlic (backhaul from Balintawak)',
    lane: 'Balintawak → Santa Cruz',
    potentialVolume: '≈3 tons/week',
    potentialMonthlyValue: 60000,
    stage: 'New',
    ownerId: 'ST-02',
    createdAt: '2026-09-25',
    lastContactAt: '2026-09-25',
    nextStep: 'Check if the NV return leg can drop at Santa Cruz',
    activities: [
      {
        at: '2026-09-25T07:02',
        note: 'Asked on our FB page about hauling onions from Balintawak on our return trips.',
        by: 'Kristine Ramos',
      },
    ],
  },
  {
    id: 'LD-007',
    businessName: 'Marikina Restaurant Supply Co.',
    contactName: 'Allan Sison',
    phone: '0927 440 1182',
    source: 'Facebook Marketplace',
    location: 'Marikina City',
    businessType: 'Distributor',
    cargoInterest: 'Bangus and tilapia, iced',
    lane: 'Lucena → Marikina',
    potentialVolume: '≈1 ton/week',
    potentialMonthlyValue: 44000,
    stage: 'Contacted',
    ownerId: 'ST-03',
    createdAt: '2026-09-15',
    lastContactAt: '2026-09-18',
    nextStep: 'Check if Marikina fits the Thursday QC run',
    activities: [],
  },
  {
    id: 'LD-008',
    businessName: 'Antipolo Catering Services',
    contactName: 'Grace Tolentino',
    phone: '0917 552 7703',
    source: 'Facebook Page',
    location: 'Antipolo, Rizal',
    businessType: 'Catering Company',
    cargoInterest: 'Seafood for events',
    lane: 'Lucena → Antipolo',
    potentialVolume: '≈150 kg/week',
    potentialMonthlyValue: 7000,
    stage: 'Lost',
    ownerId: 'ST-03',
    createdAt: '2026-08-20',
    lastContactAt: '2026-09-04',
    lostReason: 'Outside our lanes; detour cost too high for the volume',
    activities: [],
  },
  {
    id: 'LD-009',
    businessName: 'Lipa Grand Events Pavilion',
    contactName: 'Ronaldo Katigbak',
    phone: '0918 772 9016',
    source: 'Existing Customer Referral',
    location: 'Lipa City, Batangas',
    businessType: 'Catering Company',
    cargoInterest: 'Sugpo and alimango for events',
    lane: 'Lucena → Lipa (Batangas run)',
    potentialVolume: '≈250 kg/week',
    potentialMonthlyValue: 11000,
    stage: 'Negotiating',
    ownerId: 'ST-04',
    createdAt: '2026-09-01',
    lastContactAt: '2026-09-24',
    nextStep: 'Wednesday Batangas run can pass Lipa — confirm drop window',
    activities: [],
  },
  {
    id: 'LD-010',
    businessName: 'GenTri Seafood Hub',
    contactName: 'Arnold Mercado',
    phone: '0927 118 4032',
    source: 'Facebook Group',
    location: 'General Trias, Cavite',
    areaId: 'general-trias',
    businessType: 'Seafood Dealer',
    cargoInterest: 'Tahong and sugpo',
    lane: 'Lucena → General Trias',
    potentialVolume: '≈1 ton/week',
    potentialMonthlyValue: 40000,
    stage: 'Won',
    ownerId: 'ST-04',
    createdAt: '2025-06-20',
    lastContactAt: '2025-07-14',
    convertedCustomerId: 'CUS-029',
    activities: [],
  },
  {
    id: 'LD-011',
    businessName: 'Candelaria Produce Traders',
    contactName: 'Lucia Barrameda',
    phone: '0935 772 1049',
    source: 'Facebook Page',
    location: 'Candelaria, Quezon',
    areaId: 'candelaria',
    businessType: 'Agri Trader',
    cargoInterest: 'Potatoes, carrots and cabbage (backhaul)',
    lane: 'Santa Rosa → Candelaria',
    potentialVolume: '≈1.2 tons × 2/week',
    potentialMonthlyValue: 48000,
    stage: 'Won',
    ownerId: 'ST-02',
    createdAt: '2025-10-30',
    lastContactAt: '2025-11-17',
    convertedCustomerId: 'CUS-049',
    activities: [],
  },
  {
    id: 'LD-012',
    businessName: 'Lucena Frozen Goods Depot',
    contactName: 'Gregorio Tan',
    phone: '0917 205 6681',
    source: 'Messenger',
    location: 'Lucena City',
    areaId: 'lucena',
    businessType: 'Distributor',
    cargoInterest: 'Frozen boxed goods from Caloocan cold storage',
    lane: 'Caloocan → Lucena',
    potentialVolume: '≈900 kg/week',
    potentialMonthlyValue: 18000,
    stage: 'Won',
    ownerId: 'ST-02',
    createdAt: '2026-08-10',
    lastContactAt: '2026-08-18',
    convertedCustomerId: 'CUS-052',
    activities: [],
  },
  {
    id: 'LD-013',
    businessName: 'Tanauan Wet Market Vendors',
    contactName: 'Lorenzo Mercado',
    phone: '0917 660 3325',
    source: 'Referral',
    location: 'Tanauan, Batangas',
    businessType: 'Palengke Vendor',
    cargoInterest: 'Tahong and tilapia',
    lane: 'Lucena → Tanauan',
    potentialVolume: '≈400 kg/week',
    potentialMonthlyValue: 12800,
    stage: 'Contacted',
    ownerId: 'ST-04',
    createdAt: '2026-09-10',
    lastContactAt: '2026-09-17',
    activities: [],
  },
  {
    id: 'LD-014',
    businessName: 'Cainta Seafood House',
    contactName: 'Michael Ong',
    phone: '0918 205 4471',
    source: 'Messenger',
    location: 'Cainta, Rizal',
    businessType: 'Restaurant',
    cargoInterest: 'Sugpo and alimango',
    lane: 'Lucena → Cainta',
    potentialVolume: '≈100 kg/week',
    potentialMonthlyValue: 6000,
    stage: 'Quoted',
    ownerId: 'ST-03',
    createdAt: '2026-09-11',
    lastContactAt: '2026-09-20',
    activities: [],
  },
  {
    id: 'LD-015',
    businessName: 'Pasig Palengke Seafood Stall',
    contactName: 'Joseph Del Rosario',
    phone: '0927 118 0093',
    source: 'Facebook Marketplace',
    location: 'Pasig City',
    businessType: 'Palengke Vendor',
    cargoInterest: 'Tahong and hipon',
    lane: 'Lucena → Pasig',
    potentialVolume: '≈300 kg/week',
    potentialMonthlyValue: 13000,
    stage: 'Sample Order',
    ownerId: 'ST-03',
    createdAt: '2026-09-09',
    lastContactAt: '2026-09-23',
    nextStep: "Trial drop on Thursday's QC run",
    activities: [],
  },
  {
    id: 'LD-016',
    businessName: 'Metro Hotel Group Purchasing',
    contactName: 'Andrea Lim',
    phone: '0917 802 1156',
    source: 'Referral',
    location: 'Makati City',
    businessType: 'Hotel',
    cargoInterest: 'Chilled seafood with accredited POD and temperature log',
    lane: 'Lucena → Makati',
    potentialVolume: '≈600 kg × 3/week',
    potentialMonthlyValue: 90000,
    stage: 'Negotiating',
    ownerId: 'ST-02',
    createdAt: '2026-08-18',
    lastContactAt: '2026-09-24',
    nextStep: 'Hauler accreditation documents submitted; site visit Oct 2',
    activities: [],
  },
  {
    id: 'LD-017',
    businessName: 'Tiaong Kakanin & Food Hub',
    contactName: 'Lorna Sarmiento',
    phone: '0928 330 6615',
    source: 'Messenger',
    location: 'Tiaong, Quezon',
    businessType: 'General Merchandise',
    cargoInterest: 'Rice and dry goods from Calamba (backhaul)',
    lane: 'Calamba → Tiaong',
    potentialVolume: '≈1 ton/week',
    potentialMonthlyValue: 20000,
    stage: 'Contacted',
    ownerId: 'ST-02',
    createdAt: '2026-09-16',
    lastContactAt: '2026-09-21',
    activities: [],
  },
  {
    id: 'LD-018',
    businessName: 'Navotas Bangkero Seafood Stall',
    contactName: 'Rommel Tuazon',
    phone: '0947 205 1180',
    source: 'Existing Customer Referral',
    location: 'Navotas City',
    areaId: 'navotas',
    businessType: 'Palengke Vendor',
    cargoInterest: 'Tahong from Pagbilao',
    lane: 'Lucena → Navotas',
    potentialVolume: '≈240 kg/week',
    potentialMonthlyValue: 11000,
    stage: 'Contacted',
    ownerId: 'ST-03',
    createdAt: '2026-09-20',
    lastContactAt: '2026-09-22',
    activities: [],
  },
  {
    id: 'LD-019',
    businessName: 'Mandaluyong Carinderia Network',
    contactName: 'Nora Bautista',
    phone: '0936 440 1195',
    source: 'Facebook Page',
    location: 'Mandaluyong City',
    businessType: 'Catering Company',
    cargoInterest: 'Tilapia and bangus',
    lane: 'Lucena → Mandaluyong',
    potentialVolume: '≈360 kg/week',
    potentialMonthlyValue: 15000,
    stage: 'New',
    ownerId: 'ST-03',
    createdAt: '2026-09-24',
    lastContactAt: '2026-09-24',
    activities: [],
  },
  {
    id: 'LD-020',
    businessName: 'Sariaya Coco Traders',
    contactName: 'Danilo Villamin',
    phone: '0918 604 1152',
    source: 'Walk-in',
    location: 'Sariaya, Quezon',
    areaId: 'sariaya',
    businessType: 'Agri Trader',
    cargoInterest: 'Niyog (mature coconut) to Valenzuela',
    lane: 'Sariaya → Valenzuela',
    potentialVolume: '≈2 tons/week',
    potentialMonthlyValue: 90000,
    stage: 'Quoted',
    ownerId: 'ST-02',
    createdAt: '2026-09-17',
    lastContactAt: '2026-09-23',
    nextStep: 'Waiting for price approval; can fill Truck 01 on Mon/Wed',
    activities: [],
  },
];
