import type { AvailableCapacity, AvailableLoad, Place, TruckingPartner } from '../domain/types';
import { placeByName } from '../domain/data/areas';
import type { LogisticsSeed } from './logistics-seed';
import { cityPlace, dispatchContact } from '../domain/lib/load-board';

/** Load Board posts and trucking partners, tied to the generated trips and jobs. */
export function generateBoardSeed(seed: LogisticsSeed) {
  // Demo load-board posts as the coordinator logged them from the GCs. Businesses, people and
  // offered freight are fictional and illustrative — not real companies, routes or live rates.

  const place = (name: string): Place => {
    const p = placeByName(name)!;
    return { name: p.name, areaId: p.areaId, address: p.address };
  };
  const VZ_DEPOT = place('Valenzuela Produce Depot — Bodega 7');
  const BALINTAWAK = place('Balintawak Market (Cloverleaf) Bagsakan');
  const STA_ROSA = place('Santa Rosa Agri Warehouse');
  const CALAMBA = place('Calamba Feeds & Agri Depot');
  const CALOOCAN_COLD = place('Caloocan Cold Storage Hub');
  const DIVISORIA = place('Divisoria Produce Terminal');
  const DALAHICAN = place('Dalahican Fish Port');
  const VZ_FEEDS = place('Valenzuela Feeds Warehouse');

  const QUEZON_NCR_GC = 'Quezon–NCR Trucking GC';
  const SOUTH_LUZON_VIBER = 'South Luzon Haulers (Viber)';
  const FB_LOADS_GROUP = 'Luzon Trucking — Loads & Trucks (FB group)';

  const TRUCKING_PARTNERS: TruckingPartner[] = [
    {
      id: 'TP-001',
      name: 'Southline Hauling Services',
      contact: { name: 'Rogelio Panganiban', phone: '0917 418 2275' },
      truckTypes: ['10-Wheeler Wing Van', '10-Wheeler Closed Van'],
      channel: 'Messenger GC',
      channelName: QUEZON_NCR_GC,
      typicalRoutes: ['Valenzuela → Lucena', 'Lucena → Navotas'],
      notes: 'Usually has return space out of Valenzuela on weekday nights. Cash on loading.',
      since: '2025-11-04',
    },
    {
      id: 'TP-002',
      name: 'Quezon Cargo Movers',
      contact: { name: 'Marlon Cabrera', phone: '0928 553 1904' },
      truckTypes: ['6-Wheeler Closed Van'],
      channel: 'Facebook Group',
      channelName: FB_LOADS_GROUP,
      typicalRoutes: ['Lucena → Quezon City', 'Tayabas → Balintawak'],
      since: '2026-02-18',
    },
    {
      id: 'TP-003',
      name: 'Metro South Trucking',
      contact: { name: 'Liza Manalastas', phone: '0995 207 6618' },
      truckTypes: ['6-Wheeler Reefer Van'],
      channel: 'Viber GC',
      channelName: SOUTH_LUZON_VIBER,
      typicalRoutes: ['Caloocan → Sariaya', 'Navotas → Lucena'],
      notes: 'Reefer — frozen and iced cargo only. Asks 50% down for first-time shippers.',
      since: '2026-01-09',
    },
    {
      id: 'TP-004',
      name: 'Lucena Freight Services',
      contact: { name: 'Ernesto Villamor', phone: '0919 664 0382' },
      truckTypes: ['6-Wheeler Closed Van', '4-Wheeler Closed Van'],
      channel: 'Direct Contact',
      typicalRoutes: ['Lucena → Batangas City', 'Lucena → Calamba'],
      notes: "Local Lucena operator; good for Batangas runs we don't cover.",
      since: '2024-08-22',
    },
    {
      id: 'TP-005',
      name: 'NCR–Quezon Haulers',
      contact: { name: 'Dindo Salazar', phone: '0936 772 5140' },
      truckTypes: ['10-Wheeler Closed Van'],
      channel: 'Messenger GC',
      channelName: QUEZON_NCR_GC,
      typicalRoutes: ['Navotas → Lucena', 'Manila → Pagbilao'],
      since: '2025-06-30',
    },
  ];

  const jobById = (id: string) => seed.jobs.find((j) => j.id === id)!;

  /** A post we already booked: cargo, route and timing come from the job it became. */
  function bookedFrom(
    jobId: string,
    post: Pick<
      AvailableLoad,
      'id' | 'source' | 'sourceReference' | 'createdAt' | 'capacityId' | 'notes' | 'offeredFreight'
    >,
  ): AvailableLoad {
    const job = jobById(jobId);
    return {
      ...post,
      contact: job.consignee,
      customerId: job.customerId,
      pickup: job.pickup,
      destination: job.dropoff,
      cargoDescription: job.cargoDescription,
      cargoCategory: job.cargoCategory,
      weightKg: job.weightKg,
      truckType: 'Any Closed Van',
      pickupAt: job.pickupAt,
      deliveryBy: job.requiredBy,
      status: 'Booked',
      jobId,
      bookedAt: job.createdAt,
      postedBy: 'Noel Pascual',
    };
  }

  const BOARD_LOADS: AvailableLoad[] = [
    {
      id: 'FRT-260925-001',
      source: 'Messenger GC',
      sourceReference: QUEZON_NCR_GC,
      contact: { name: 'Alvin Tolentino', phone: '0917 334 8821' },
      pickup: VZ_DEPOT,
      destination: cityPlace('lucena'),
      cargoDescription: 'Red onion, sacked',
      cargoCategory: 'Produce',
      weightKg: 2000,
      truckType: 'Any Closed Van',
      pickupAt: '2026-09-25T12:30',
      deliveryBy: '2026-09-25T22:00',
      offeredFreight: 9000,
      status: 'Looking for Truck',
      notes: "80 sacks. Shipper's boys load; unloading at a Lucena bodega near the diversion road.",
      createdAt: '2026-09-25T06:52',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'FRT-260925-002',
      source: 'Viber GC',
      sourceReference: SOUTH_LUZON_VIBER,
      contact: { name: 'Carmela Ortiz', phone: '0918 240 7753' },
      pickup: BALINTAWAK,
      destination: {
        name: 'Tayabas Public Market',
        areaId: 'tayabas',
        address: 'Brgy. San Diego Zone I, Tayabas City',
      },
      cargoDescription: 'Garlic, sacked',
      cargoCategory: 'Produce',
      weightKg: 800,
      truckType: 'Any Closed Van',
      pickupAt: '2026-09-25T13:30',
      deliveryBy: '2026-09-26T06:00',
      offeredFreight: 4000,
      status: 'Matching',
      notes: 'Asked Carmela to hold it for us until 10 AM.',
      createdAt: '2026-09-25T07:15',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'FRT-260925-003',
      source: 'Facebook Group',
      sourceReference: FB_LOADS_GROUP,
      contact: { name: 'Jun Robles', phone: '0927 118 3306' },
      pickup: STA_ROSA,
      destination: {
        name: 'Lucena City — Diversion Rd. bodega',
        areaId: 'lucena',
        address: 'Diversion Rd., Brgy. Domoit, Lucena City',
      },
      cargoDescription: 'Ginger (luya), sacked',
      cargoCategory: 'Produce',
      weightKg: 1500,
      truckType: 'Any Truck',
      pickupAt: '2026-09-25T16:30',
      deliveryBy: '2026-09-25T23:00',
      offeredFreight: 6500,
      status: 'Looking for Truck',
      createdAt: '2026-09-25T07:30',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'FRT-260925-004',
      source: 'Messenger GC',
      sourceReference: QUEZON_NCR_GC,
      contact: { name: 'Ramil Soriano', phone: '0917 902 6613' },
      pickup: CALOOCAN_COLD,
      destination: {
        name: 'Sariaya frozen goods dealer',
        areaId: 'sariaya',
        address: 'Rizal St., Brgy. Poblacion 2, Sariaya',
      },
      cargoDescription: 'Frozen goods (boxed)',
      cargoCategory: 'General Cargo',
      weightKg: 2500,
      truckType: '6-Wheeler Reefer Van',
      pickupAt: '2026-09-25T17:00',
      deliveryBy: '2026-09-25T23:30',
      offeredFreight: 11000,
      specialHandling: 'Keep frozen — reefer set to −18 °C',
      status: 'Looking for Truck',
      createdAt: '2026-09-25T07:02',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'FRT-260925-005',
      source: 'Direct Contact',
      contact: { name: 'Gerry Bautista', phone: '0919 552 0471' },
      pickup: CALAMBA,
      destination: {
        name: 'Pagbilao fishpond supply store',
        areaId: 'pagbilao',
        address: 'Maharlika Hwy., Brgy. Silangang Malicboy, Pagbilao',
      },
      cargoDescription: 'Aquaculture feeds',
      cargoCategory: 'Dry Goods',
      weightKg: 2800,
      truckType: 'Any Closed Van',
      pickupAt: '2026-09-25T18:30',
      deliveryBy: '2026-09-26T08:00',
      offeredFreight: 9500,
      status: 'Looking for Truck',
      notes: 'Gerry called the office directly. 112 sacks, forklift at the depot.',
      createdAt: '2026-09-25T06:40',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'FRT-260925-006',
      source: 'Existing Customer',
      contact: { name: 'Alfredo Maaño', phone: '0918 772 1043' },
      customerId: 'CUS-035',
      pickup: DIVISORIA,
      destination: {
        name: 'Quezon Harvest Traders',
        areaId: 'sariaya',
        address: 'Gen. Luna St., Brgy. Poblacion 4, Sariaya',
      },
      cargoDescription: 'White onion, sacked',
      cargoCategory: 'Produce',
      weightKg: 1200,
      truckType: 'Any Closed Van',
      pickupAt: '2026-09-25T14:00',
      deliveryBy: '2026-09-26T05:00',
      status: 'Looking for Truck',
      notes: 'Regular customer — our standard backhaul rate applies.',
      createdAt: '2026-09-25T06:35',
      postedBy: 'Kristine Ramos',
    },
    {
      id: 'FRT-260925-007',
      source: 'Facebook Post',
      sourceReference: 'Posted on the Dalahican Fish Traders page',
      contact: { name: 'Bernadette Lim', phone: '0917 225 8894' },
      pickup: DALAHICAN,
      destination: {
        name: 'Navotas Fish Port Complex',
        areaId: 'navotas',
        address: 'North Bay Blvd. South, Navotas City',
      },
      cargoDescription: 'Bangus (milkfish), iced',
      cargoCategory: 'Seafood',
      weightKg: 1800,
      truckType: 'Any Closed Van',
      pickupAt: '2026-09-26T02:30',
      deliveryBy: '2026-09-26T08:00',
      offeredFreight: 18000,
      specialHandling: 'Iced banyeras — keep upright, drain meltwater',
      status: 'Looking for Truck',
      createdAt: '2026-09-25T07:40',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'FRT-260925-008',
      source: 'Messenger GC',
      sourceReference: QUEZON_NCR_GC,
      contact: { name: 'Dante Esguerra', phone: '0928 330 4471' },
      pickup: {
        name: 'Anabu grocery warehouse',
        areaId: 'imus',
        address: 'Aguinaldo Hwy., Brgy. Anabu I-B, Imus',
      },
      destination: {
        name: 'Isabang grocery depot',
        areaId: 'lucena',
        address: 'Brgy. Isabang, Lucena City',
      },
      cargoDescription: 'Boxed grocery goods',
      cargoCategory: 'General Cargo',
      weightKg: 4500,
      truckType: '10-Wheeler Closed Van',
      pickupAt: '2026-09-25T15:30',
      deliveryBy: '2026-09-25T23:59',
      offeredFreight: 16000,
      status: 'Looking for Truck',
      createdAt: '2026-09-25T07:20',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'FRT-260925-009',
      source: 'Messenger GC',
      sourceReference: QUEZON_NCR_GC,
      contact: { name: 'Ronnie Galvez', phone: '0917 663 0294' },
      pickup: VZ_DEPOT,
      destination: {
        name: 'Candelaria Public Market',
        areaId: 'candelaria',
        address: 'Brgy. Poblacion, Candelaria',
      },
      cargoDescription: 'Garlic, sacked',
      cargoCategory: 'Produce',
      weightKg: 2200,
      truckType: 'Any Closed Van',
      pickupAt: '2026-09-26T10:30',
      deliveryBy: '2026-09-26T20:00',
      offeredFreight: 9500,
      status: 'Looking for Truck',
      createdAt: '2026-09-25T07:44',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'FRT-260925-010',
      source: 'Existing Customer',
      contact: { name: 'Rolando Abuel', phone: '0917 540 2268' },
      customerId: 'CUS-047',
      pickup: DALAHICAN,
      destination: {
        name: 'Batangas City Public Market',
        areaId: 'batangas-city',
        address: 'P. Burgos St., Batangas City',
      },
      cargoDescription: 'Tulingan (frigate tuna), iced',
      cargoCategory: 'Seafood',
      weightKg: 2000,
      truckType: 'Any Closed Van',
      pickupAt: '2026-09-26T04:00',
      deliveryBy: '2026-09-26T08:00',
      offeredFreight: 7000,
      status: 'Matching',
      notes:
        'We have no Batangas trip tomorrow — asked Lucena Freight Services if their 6-wheeler can take it.',
      createdAt: '2026-09-25T06:58',
      postedBy: 'Kristine Ramos',
    },
    bookedFrom('JOB-260925-010', {
      id: 'FRT-260924-003',
      source: 'Messenger GC',
      sourceReference: QUEZON_NCR_GC,
      createdAt: '2026-09-24T19:40',
      capacityId: 'CAP-260924-001',
      offeredFreight: 2500,
      notes: 'Josefina asked in the GC for pasabay on a Balintawak → Lucena run.',
    }),
    bookedFrom('JOB-260926-006', {
      id: 'FRT-260925-011',
      source: 'Viber GC',
      sourceReference: SOUTH_LUZON_VIBER,
      createdAt: '2026-09-25T06:55',
      capacityId: 'CAP-260925-002',
      offeredFreight: 4000,
    }),
    {
      id: 'FRT-260924-001',
      source: 'Facebook Group',
      sourceReference: FB_LOADS_GROUP,
      contact: { name: 'Arnel Mercado', phone: '0939 118 6627' },
      pickup: VZ_FEEDS,
      destination: { name: 'Pagbilao fish farm', areaId: 'pagbilao' },
      cargoDescription: 'Aquaculture feeds',
      cargoCategory: 'Dry Goods',
      weightKg: 2500,
      truckType: 'Any Truck',
      pickupAt: '2026-09-24T18:00',
      status: 'Looking for Truck',
      createdAt: '2026-09-24T09:10',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'FRT-260924-002',
      source: 'Viber GC',
      sourceReference: SOUTH_LUZON_VIBER,
      contact: { name: 'Nora Castillo', phone: '0926 441 0983' },
      pickup: BALINTAWAK,
      destination: { name: 'Candelaria vegetable stall', areaId: 'candelaria' },
      cargoDescription: 'Potato, sacked',
      cargoCategory: 'Produce',
      weightKg: 1000,
      truckType: 'Any Closed Van',
      pickupAt: '2026-09-25T15:00',
      offeredFreight: 4500,
      status: 'Cancelled',
      closedReason: 'Shipper found a truck in the GC first',
      createdAt: '2026-09-24T16:30',
      postedBy: 'Noel Pascual',
    },
  ];

  const OUR_RESTRICTIONS =
    'Insulated van that also carries seafood — no chemicals, fertilizer or livestock.';

  const BOARD_CAPACITY: AvailableCapacity[] = [
    // Our trucks — capacity figures are read from the trip, never stored here.
    {
      id: 'CAP-260924-001',
      fleet: 'internal',
      tripId: 'TRIP-260925-01',
      leg: 'return',
      source: 'Internal',
      contact: dispatchContact(),
      acceptedCargo: [],
      restrictions: OUR_RESTRICTIONS,
      status: 'Open',
      createdAt: '2026-09-24T18:00',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'CAP-260925-001',
      fleet: 'internal',
      tripId: 'TRIP-260925-02',
      leg: 'return',
      source: 'Internal',
      contact: dispatchContact(),
      acceptedCargo: [],
      restrictions: OUR_RESTRICTIONS,
      status: 'Open',
      createdAt: '2026-09-25T06:00',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'CAP-260925-002',
      fleet: 'internal',
      tripId: 'TRIP-260926-01',
      leg: 'return',
      source: 'Internal',
      contact: dispatchContact(),
      acceptedCargo: [],
      restrictions: OUR_RESTRICTIONS,
      status: 'Open',
      createdAt: '2026-09-25T06:30',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'CAP-260925-003',
      fleet: 'internal',
      tripId: 'TRIP-260926-01',
      leg: 'outbound',
      source: 'Internal',
      contact: dispatchContact(),
      acceptedCargo: ['Seafood', 'Shellfish'],
      restrictions: 'Outbound van is iced seafood — no produce or dry goods on this leg.',
      status: 'Open',
      createdAt: '2026-09-25T07:00',
      postedBy: 'Noel Pascual',
    },
    // Partner trucks — as posted in the GCs.
    {
      id: 'CAP-260925-004',
      fleet: 'external',
      partnerId: 'TP-001',
      source: 'Messenger GC',
      sourceReference: QUEZON_NCR_GC,
      contact: TRUCKING_PARTNERS[0].contact,
      truckType: '10-Wheeler Wing Van',
      currentLocation: cityPlace('valenzuela'),
      destination: cityPlace('lucena'),
      plannedRoute: ['calamba'],
      totalCapacityKg: 10000,
      usedCapacityKg: 5800,
      departureAt: '2026-09-25T21:00',
      acceptedCargo: ['Produce', 'Dry Goods', 'General Cargo'],
      restrictions: 'Wing van — no iced or wet cargo.',
      status: 'Open',
      createdAt: '2026-09-25T07:25',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'CAP-260925-005',
      fleet: 'external',
      partnerId: 'TP-003',
      source: 'Viber GC',
      sourceReference: SOUTH_LUZON_VIBER,
      contact: TRUCKING_PARTNERS[2].contact,
      truckType: '6-Wheeler Reefer Van',
      currentLocation: cityPlace('caloocan'),
      destination: cityPlace('sariaya'),
      plannedRoute: [],
      totalCapacityKg: 5000,
      usedCapacityKg: 2200,
      departureAt: '2026-09-25T17:30',
      acceptedCargo: ['Seafood', 'Shellfish', 'General Cargo'],
      restrictions: 'Reefer — frozen or iced cargo only.',
      status: 'Open',
      createdAt: '2026-09-25T06:45',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'CAP-260925-006',
      fleet: 'external',
      partnerId: 'TP-002',
      source: 'Facebook Group',
      sourceReference: FB_LOADS_GROUP,
      contact: TRUCKING_PARTNERS[1].contact,
      truckType: '6-Wheeler Closed Van',
      currentLocation: cityPlace('lucena'),
      destination: cityPlace('quezon-city'),
      plannedRoute: ['calamba'],
      totalCapacityKg: 6000,
      usedCapacityKg: 4500,
      departureAt: '2026-09-26T04:00',
      acceptedCargo: [],
      status: 'Open',
      createdAt: '2026-09-25T07:05',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'CAP-260925-007',
      fleet: 'external',
      partnerId: 'TP-004',
      source: 'Direct Contact',
      contact: TRUCKING_PARTNERS[3].contact,
      truckType: '6-Wheeler Closed Van',
      currentLocation: cityPlace('lucena'),
      destination: cityPlace('batangas-city'),
      plannedRoute: [],
      totalCapacityKg: 4000,
      usedCapacityKg: 1200,
      departureAt: '2026-09-26T04:30',
      acceptedCargo: [],
      status: 'Open',
      notes: 'Ernesto can pick up at Dalahican before 4:30 AM.',
      createdAt: '2026-09-25T07:35',
      postedBy: 'Kristine Ramos',
    },
    {
      id: 'CAP-260925-008',
      fleet: 'external',
      partnerId: 'TP-005',
      source: 'Messenger GC',
      sourceReference: QUEZON_NCR_GC,
      contact: TRUCKING_PARTNERS[4].contact,
      truckType: '10-Wheeler Closed Van',
      currentLocation: cityPlace('navotas'),
      destination: cityPlace('lucena'),
      plannedRoute: ['manila'],
      totalCapacityKg: 8000,
      usedCapacityKg: 8000,
      departureAt: '2026-09-25T14:00',
      acceptedCargo: [],
      status: 'Full',
      notes: 'Dindo posted at 5:50 AM, full by 7:30 AM.',
      createdAt: '2026-09-25T05:50',
      postedBy: 'Noel Pascual',
    },
    {
      id: 'CAP-260924-002',
      fleet: 'external',
      partnerId: 'TP-005',
      source: 'Messenger GC',
      sourceReference: QUEZON_NCR_GC,
      contact: TRUCKING_PARTNERS[4].contact,
      truckType: '10-Wheeler Closed Van',
      currentLocation: cityPlace('navotas'),
      destination: cityPlace('pagbilao'),
      plannedRoute: ['manila', 'calamba'],
      totalCapacityKg: 8000,
      usedCapacityKg: 3000,
      departureAt: '2026-09-24T20:00',
      acceptedCargo: [],
      status: 'Open',
      createdAt: '2026-09-24T12:00',
      postedBy: 'Noel Pascual',
    },
  ];
  return { TRUCKING_PARTNERS, BOARD_LOADS, BOARD_CAPACITY };
}
