export enum OrganizationType {
  SHIPPER = 'SHIPPER',
  TRUCKING_COMPANY = 'TRUCKING_COMPANY',
  LOGISTICS_PROVIDER = 'LOGISTICS_PROVIDER',
  BROKER = 'BROKER',
  WAREHOUSE = 'WAREHOUSE',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
}

export enum Role {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  DISPATCHER = 'DISPATCHER',
  DRIVER_MANAGER = 'DRIVER_MANAGER',
  DRIVER = 'DRIVER',
  FINANCE = 'FINANCE',
  VIEWER = 'VIEWER',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  // TradeLoop operations desks
  SALES = 'SALES',
  WAREHOUSE = 'WAREHOUSE',
  PROCUREMENT = 'PROCUREMENT',
  /** A customer's portal login; the membership's subjectRef is their customer record (CUS-…). */
  CUSTOMER = 'CUSTOMER',
}

export const RoleGroups = {
  ORG_ADMIN: [Role.OWNER, Role.ADMIN],
  OPERATIONS: [Role.OWNER, Role.ADMIN, Role.OPERATIONS_MANAGER, Role.DISPATCHER],
  FLEET: [Role.OWNER, Role.ADMIN, Role.OPERATIONS_MANAGER, Role.DRIVER_MANAGER],
  DISPATCH: [Role.OWNER, Role.ADMIN, Role.OPERATIONS_MANAGER, Role.DISPATCHER, Role.DRIVER_MANAGER],
  FINANCE: [Role.OWNER, Role.ADMIN, Role.FINANCE],
  COMMERCIAL: [Role.OWNER, Role.ADMIN, Role.OPERATIONS_MANAGER, Role.DISPATCHER],
  AUDIT: [Role.OWNER, Role.ADMIN, Role.OPERATIONS_MANAGER],
} as const satisfies Record<string, readonly Role[]>;

export enum VehicleType {
  MOTORCYCLE = 'MOTORCYCLE',
  SEDAN = 'SEDAN',
  VAN = 'VAN',
  L300 = 'L300',
  FOUR_WHEELER_TRUCK = '4W_TRUCK',
  SIX_WHEELER_TRUCK = '6W_TRUCK',
  TEN_WHEELER_TRUCK = '10W_TRUCK',
  TRACTOR_HEAD = 'TRACTOR_HEAD',
  TRAILER = 'TRAILER',
  REFRIGERATED = 'REFRIGERATED',
  OTHER = 'OTHER',
}

export enum CommissionType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED = 'FIXED',
  NONE = 'NONE',
}
